github_url: https://github.com/humblelad
google_url: https://www.youtube.com/geekslider
linkedin_url: https://in.linkedin.com/in/ronniejosephhere
about_url: /about/
archive_url: /acknowledgments/
projects_url: /projects/
contact_url: /contact/
disclaimer_url: /disclaimer/
rss_url: https://twitter.com/CircleNinja
sitemap_url: /sitemap.xml
